### ISSUE TITLE
Index Out of Bound Error

### ISSUE THREAD

**Issue by vickyraut** [kardSIM/Vehicle_Speed_Estimation#1]
I am getting index error on line 226 -> IndexError: index 7 is out of bounds for axis 0 with size 4
![Screenshot from 2024-09-15 22-30-52](https://github.com/user-attachments/assets/9bd070f0-6e43-4fe5-83aa-1ba74a5f8718)

**Comment by vickyraut** [comment]
Can you please help out @kardSIM

**Comment by kardSIM** [comment]
Try using last commit

**Comment by vickyraut** [comment]
Thanks Isuue got solved..
